services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - main-hub
      - mbti-arcade
    networks:
      - web-service-network
    container_name: nginx-proxy

  # Main Service Hub
  main-hub:
    build: ./main-service
    expose:
      - "8080"
    volumes:
      - ./main-service:/app
      - /app/__pycache__
    networks:
      - web-service-network
    container_name: main-hub

  # MBTI Arcade Service
  mbti-arcade:
    build: ./mbti-arcade
    expose:
      - "8000"
    volumes:
      - ./mbti-arcade:/app
      - /app/__pycache__
    networks:
      - web-service-network
    container_name: mbti-arcade

networks:
  web-service-network:
    driver: bridge
